# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: payload.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='payload.proto',
  package='tutorial',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=_b('\n\rpayload.proto\x12\x08tutorial\"&\n\x07payload\x12\x0f\n\x07payload\x18\x01 \x02(\t\x12\n\n\x02id\x18\x02 \x02(\x05')
)




_PAYLOAD = _descriptor.Descriptor(
  name='payload',
  full_name='tutorial.payload',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='payload', full_name='tutorial.payload.payload', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='id', full_name='tutorial.payload.id', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=27,
  serialized_end=65,
)

DESCRIPTOR.message_types_by_name['payload'] = _PAYLOAD
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

payload = _reflection.GeneratedProtocolMessageType('payload', (_message.Message,), dict(
  DESCRIPTOR = _PAYLOAD,
  __module__ = 'payload_pb2'
  # @@protoc_insertion_point(class_scope:tutorial.payload)
  ))
_sym_db.RegisterMessage(payload)


# @@protoc_insertion_point(module_scope)
